remote_theme: pmarsceill/just-the-docs
#theme: just-the-docs 
title: Digital Interfaces
color_scheme: digital-interfaces
plugins:
  - jekyll-redirect-from

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: note
    color: blue